services:
  pozor_dom_auth_postgres:
    image: postgres:18.1-alpine3.22
    container_name: pozor_dom_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - ${AUTH_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices

  pozor_dom_device_postgres:
    image: postgres:18.1-alpine3.22
    container_name: pozor_dom_device_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DEVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEVICE_POSTGRES_DB}
    volumes:
      - device_postgres_data:/var/lib/postgresql/data
    ports:
      - ${DEVICE_POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER}"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - microservices

  pozord_dom_pgadmin:
    image: dpage/pgadmin4:9.10
    container_name: pozord_dom_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      pozor_dom_auth_postgres:
        condition: service_healthy
      pozor_dom_device_postgres:
        condition: service_healthy
    networks:
      - microservices

  pozor_dom_auth_service:
    build:
      context: AuthorizationService
      dockerfile: Dockerfile
    container_name: pozor_dom_auth_service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - ${AUTH_SERVICE_PORT}:80
    depends_on:
      pozor_dom_auth_postgres:
        condition: service_healthy
    networks:
      - microservices

  pozor_dom_device_service:
    build:
      context: DeviceService
      dockerfile: Dockerfile
    container_name: pozor_dom_device_service
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - ${DEVICE_SERVICE_PORT}:80
    depends_on:
      pozor_dom_device_postgres:
        condition: service_healthy
    networks:
      - microservices

  pozor_dom_gateway:
    build:
      context: _gateway
      dockerfile: Dockerfile
    container_name: pozor_dom_gateway
    restart: unless-stopped
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - pozor_dom_auth_service
      - pozor_dom_device_service
    networks:
      - microservices

networks:
  microservices:
    driver: bridge

volumes:
  auth_postgres_data:
  device_postgres_data:
  pgadmin_data:
