services:
  pozor_dom_auth_postgres:
    image: postgres:18.1-alpine3.22
    container_name: pozor_dom_auth_postgres
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - ${AUTH_POSTGRES_PORT}:5432
    networks:
      - microservices

  pozor_dom_store_postgres:
    image: postgres:18.1-alpine3.22
    container_name: pozor_dom_store_postgres
    environment:
      - POSTGRES_USER=${STORE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STORE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${STORE_POSTGRES_DB}
    volumes:
      - store_postgres_data:/var/lib/postgresql/data
    ports:
      - ${STORE_POSTGRES_PORT}:5432
    networks:
      - microservices

  pozord_dom_pgadmin:
    container_name: pozord_dom_pgadmin
    image: dpage/pgadmin4:9.10
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pozor_dom_auth_postgres
      - pozor_dom_store_postgres
    networks:
      - microservices

  pozor_dom_auth_service:
    build:
      context: PozorDomAuthService
      dockerfile: Dockerfile
    container_name: pozor_dom_auth_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - ${AUTH_SERVICE_PORT}:8080
    depends_on:
      - pozor_dom_auth_postgres
    networks:
      - microservices

  pozor_dom_store_service:
    build:
      context: PozorDomStoreService
      dockerfile: Dockerfile
    container_name: pozor_dom_store_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - ${STORE_SERVICE_PORT}:8080
    depends_on:
      - pozor_dom_store_postgres
    networks:
      - microservices

  pozor_dom_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pozor_dom_gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - pozor_dom_auth_service
      - pozor_dom_store_service
    networks:
      - microservices

volumes:
  auth_postgres_data:
  store_postgres_data:
  pgadmin_data:

networks:
  microservices:
    driver: bridge
