services:
  pozor_dom_auth_postgres:
    image: postgres:18.1-alpine3.22
    container_name: pozor_dom_auth_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pozor_dom_auth_service
    ports:
      - 5432:5432
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_net
    restart: unless-stopped

  pozor_dom_auth_service:
    build:
      context: PozorDomAuthService
      dockerfile: Dockerfile
    container_name: pozor_dom_auth_service
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - pozor_dom_auth_postgres
    networks:
      - microservices_net
    restart: unless-stopped

  pozor_dom_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pozor_dom_gateway
    ports:
      - 80:80
    depends_on:
      - pozor_dom_auth_service
    networks:
      - microservices_net
    restart: unless-stopped

  pozord_dom_pgadmin:
    container_name: pozord_dom_pgadmin
    image: dpage/pgadmin4:9.10
    environment:
      PGADMIN_DEFAULT_EMAIL: root@local.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pozor_dom_auth_postgres
    networks:
      - microservices_net

volumes:
  pgadmin_data:
    driver: local
  auth_postgres_data:
    driver: local

networks:
  microservices_net:
    driver: bridge
